### ISSUE TITLE
LDMS Stream not collecting Darshan data

### ISSUE THREAD

**Issue by spwalto** [anaveroneze/ldms-darshan-analysis#1]
@anaveroneze  
1. It looks like the ``HOSTNAME`` for the ldms daemon is ``localhost``:
https://github.com/anaveroneze/ldms-darshan-analysis/blob/ece96deea970bd1cc21341427f979eace99412ec/code/aws_configuring.ipynb#L91
but the ``DARSHAN_LDMS_HOST`` is set to ``ip-xx-xx...``:
https://github.com/anaveroneze/ldms-darshan-analysis/blob/ece96deea970bd1cc21341427f979eace99412ec/code/aws_configuring.ipynb#L190

This might cause some issues in connecting/detecting the LDMS daemon. Can you try setting these env variables to ``localhost`` and see if that works? 

2. Does the darshan_stream_store.log file output anything? I saw the ``cat /tmp/darshan_stream_store.log`` but didn't see any output info in the ``aws_configuring.ipynb`` file:
https://github.com/anaveroneze/ldms-darshan-analysis/blob/ece96deea970bd1cc21341427f979eace99412ec/code/aws_configuring.ipynb#L362

3. What do you get when you run ``ls -ltrch streams/store/``?
4. Just for a sanity check to make sure LDMS was actually configured in the Darshan build - Did you get a similar output to the one below (specifically the ``LDMS runtime module - yes``)?:
```
------------------------------------------------------------------------------
   Darshan Runtime Version 3.4.4 configured with the following features:
           MPI C compiler                - mpicc
           GCC-compatible compiler       - yes
           NULL          module support  - yes
           POSIX         module support  - yes
           STDIO         module support  - yes
           DXT           module support  - yes
           MPI-IO        module support  - yes
           AUTOPERF MPI  module support  - no
           AUTOPERF XC   module support  - no
           HDF5          module support  - yes (using HDF5 1.10.6)
           PnetCDF       module support  - no
           BG/Q          module support  - no
           Lustre        module support  - yes
           MDHIM         module support  - no
           HEATMAP       module support  - yes
           LDMS          runtime module  - yes
           Memory alignment in bytes     - 8
           Log file env variables        - LOGFILE_PATH_DARSHAN
           Location of Darshan log files - N/A
           Job ID env variable           - PBS_JOBID
           MPI-IO hints                  - romio_no_indep_rw=true;cb_nodes=4
```

**Comment by anaveroneze** [comment]
1. Changed all to `localhost` 
2. It returns empty, nothing is written in the file before or after running the mpi application.
3. Output:

```
root@ip-172-31-87-41:/home/ubuntu# ls -ltrch streams/store/
total 4.0K
drwxrwxrwx 2 ubuntu ubuntu 4.0K Jan 17 20:59 csv
root@ip-172-31-87-41:/home/ubuntu# ls -ltrch streams/store/csv/
total 0
-rw------- 1 ubuntu ubuntu 0 Jan 17 20:59 darshanConnector.1705525156
```

4. Darshan installation looks correct (I am not using HDF5):

```
------------------------------------------------------------------------------
   Darshan Runtime Version 3.4.4 configured with the following features:
           MPI C compiler                - mpicc
           GCC-compatible compiler       - yes
           NULL          module support  - yes
           POSIX         module support  - yes
           STDIO         module support  - yes
           DXT           module support  - yes
           MPI-IO        module support  - yes
           AUTOPERF MPI  module support  - no
           AUTOPERF XC   module support  - no
           HDF5          module support  - no
           PnetCDF       module support  - no
           BG/Q          module support  - no
           Lustre        module support  - no
           MDHIM         module support  - no
           HEATMAP       module support  - yes
           LDMS          runtime module  - yes
           Memory alignment in bytes     - 8
           Log file env variables        - N/A
           Location of Darshan log files - /home/ubuntu/darshan/build/logs
           Job ID env variable           - PBS_JOBID
           MPI-IO hints                  - romio_no_indep_rw=true;cb_nodes=4
```

I am running LDMS using sudo su access and I trried running the MPI app with sudo or normal user execution too.

**Comment by spwalto** [comment]
Okay so it looks like the ``LD_LIBRARY_PATH`` is set to ``/home/ubuntu/lib`` and not ``/home/ubuntu/darshan/build/install/lib``:

https://github.com/anaveroneze/ldms-darshan-analysis/blob/ece96deea970bd1cc21341427f979eace99412ec/code/aws_configuring.ipynb#L166-L168

This is my fault as I saw in the [Set Darshan Environment](https://ovis-hpc.readthedocs.io/en/latest/ldms/ldms-streams.html#set-the-environment) section of the LDMS documentation I had set the ``DARSHAN_INSTALL_PATH`` to ``darshan-prefix`` which is not correct. Apologies about this!!

I've updated the documentation so it now has the following:
```
export DARSHAN_INSTALL_PATH=<path-to-darshan-install>
export LD_PRELOAD=<path-to-darshan-install>/lib/libdarshan.so
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DARSHAN_INSTALL_PATH/lib 
...
```

If this still doesn't work then let me know and I'll try to reproduce the issue :)

**Comment by anaveroneze** [comment]
Thanks! I did not notice it either even setting it correctly before for the LDMS environment variables.

I changed it, but still not collecting information. I could get some warning messages from the [/tmp/darshan_stream_store.log](url) that might be useful:

```
root@ip-172-31-39-181:/home/ubuntu# ldms_ls -p 10444 -x sock -v -v
ps auwx | grep ldmsd | grep -v grep
Hostname    : localhost
IP Address  : 127.0.0.1
Port        : 10444
Transport   : sock
Schema Digest                                                    Schema         Instance                 Flags  Msize  Dsize  Hsize  UID    GID    Perm       Update            Duration          Info    
---------------------------------------------------------------- -------------- ------------------------ ------ ------ ------ ------ ------ ------ ---------- ----------------- ----------------- --------
root       55814  0.0  0.5 260092  4904 ?        Ssl  22:34   0:00 ldmsd -x sock:10444 -c darshan_stream_store.conf -l /tmp/darshan_stream_store.log -v DEBUG
root@ip-172-31-39-181:/home/ubuntu# ps auwx | grep ldmsd | grep -v grep
root       55814  0.0  0.5 260092  4904 ?        Ssl  22:34   0:00 ldmsd -x sock:10444 -c darshan_stream_store.conf -l /tmp/darshan_stream_store.log -v DEBUG
root@ip-172-31-39-181:/home/ubuntu# cat /tmp/darshan_stream_store.log
Thu Jan 18 22:34:11 2024:  WARNING: ldmsd: Failed to create Zap's log subsystem.
Thu Jan 18 22:34:11 2024:     INFO: ldmsd: Listening on sock:10444 using `sock` transport and `none` authentication
Thu Jan 18 22:34:11 2024:    DEBUG: config: Checking for hello_sampler in /home/ubuntu/ovis/build/lib/ovis-ldms
Thu Jan 18 22:34:11 2024:    DEBUG: config: msg_no 5 flags 3 rec_len 28 rsp_err 0
Thu Jan 18 22:34:11 2024:    DEBUG: ldms.stream: sce 0x559a003a3560: bind stream 'darshanConnector' - client 'hello_sampler' match 'darshanConnector'
Thu Jan 18 22:34:11 2024:    DEBUG: config: msg_no 6 flags 3 rec_len 28 rsp_err 0
Thu Jan 18 22:34:11 2024:    DEBUG: config: msg_no 7 flags 3 rec_len 28 rsp_err 0
Thu Jan 18 22:34:11 2024:    DEBUG: config: Checking for stream_csv_store in /home/ubuntu/ovis/build/lib/ovis-ldms
Thu Jan 18 22:34:11 2024:    DEBUG: config: msg_no 8 flags 3 rec_len 28 rsp_err 0
Thu Jan 18 22:34:11 2024:    DEBUG: store.stream_csv_store: stream_csv_store: setting root_path to './streams/store'
Thu Jan 18 22:34:11 2024:    DEBUG: store.stream_csv_store: stream_csv_store: setting container to 'csv'
Thu Jan 18 22:34:11 2024:    DEBUG: store.stream_csv_store: stream_csv_store: opening streamstore for 'darshanConnector'
Thu Jan 18 22:34:11 2024:    DEBUG: store.stream_csv_store: stream_csv_store: stream 'darshanConnector' will have file './streams/store/csv/darshanConnector.1705617251'
Thu Jan 18 22:34:11 2024:    DEBUG: store.stream_csv_store: Subscribing to stream 'darshanConnector'
Thu Jan 18 22:34:11 2024:    DEBUG: ldms.stream: sce 0x559a003a8210: bind stream 'darshanConnector' - client 'stream_csv_store' match 'darshanConnector'
Thu Jan 18 22:34:11 2024:    DEBUG: store.stream_csv_store: stream_csv_store: using rolltype 3 rollover 500000
Thu Jan 18 22:34:11 2024:    DEBUG: config: msg_no 9 flags 3 rec_len 28 rsp_err 0
Thu Jan 18 22:34:11 2024:     INFO: ldmsd: Processing the config file 'darshan_stream_store.conf' is done.
Thu Jan 18 22:34:11 2024:     INFO: ldmsd: Enabling in-band config

```

**Comment by spwalto** [comment]
Okay! I think I figured it out. I ran through the steps to recreate the problem and it looks like the following line is what's causing the issue: 
https://github.com/anaveroneze/ldms-darshan-analysis/blob/ece96deea970bd1cc21341427f979eace99412ec/code/aws_configuring.ipynb#L341

If you leave ``sudo`` out and execute the program (i.e. as ubuntu) in the new terminal window then the data collection will work. What I think is happening is that the system is elevating to ``root`` to execute the program but ``root`` does not have any of the env variables set (i.e. ``DARSHAN_LDMS_XX``) which is why it's not connecting to the LDMS daemon. 

So you can either 1) leave out the ``sudo`` from above or 2) elevate to sudo (``sudo su``) _before_ sourcing the env files:
https://github.com/anaveroneze/ldms-darshan-analysis/blob/ece96deea970bd1cc21341427f979eace99412ec/code/aws_configuring.ipynb#L330-L332

**Comment by anaveroneze** [comment]
Hi Sara,

it is working, thank you :)

- I had to set the `export PYTHONPATH=/usr/local/lib/python3.10/dist-packages` to my python installation. In the documentation it is as `export PYTHONPATH="$TOP/lib/python2.7/site-packages/` but this can vary depending on the distribution and location where someone installed Python, so I would suggest to just leave as `<python-packages-path>` or something like that.

- I also need to give user permissions to 2 files so I could run everything without sudo - but I think this is because of AWS environment.

**Comment by spwalto** [comment]
@anaveroneze I forgot to mention that Darshan has a configuration flag, ``--with-log-path-by-env`` that will generate a new logfile name for each run. This is what I use when I install Darshan on our HPC systems so that users don't have to manually update the log file:
```
../configure --with-log-path-by-env=LOGFILE_PATH_DARSHAN --prefix=${HOME}/darshan/build/install --with-jobid-env=PBS_JOBID CC=mpicc --enable-ldms-mod --with-ldms=${HOME}/ovis/build
```

If darshan is build with this flag instead of:
https://github.com/anaveroneze/ldms-darshan-analysis/blob/ece96deea970bd1cc21341427f979eace99412ec/code/aws_configuring.ipynb#L118

Then you'll just need to replace ``$DARSHAN_LOGFILE`` with ``$LOGFILE_PATH_DARSHAN`` and set it to:
```
export LOGFILE_PATH_DARSHAN=$DARSHAN_TMP/
```
Now Darshan will generate a new log file that contains the user who ran it, executable name, date it was ran and some other info that I can't quite remember at the moment (with *.darshan extension) under the ``/tmp/darshan-ldms-test`` directory. Note: Whatever $LOGFILE_PATH_DARSHAN is set to, that directory MUST exist.
